
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Label label1;
	private global::Gtk.Label label2;
	private global::Gtk.Entry txtcodigo;
	private global::Gtk.Entry txtnombre;
	private global::Gtk.SpinButton spinEstados;
	private global::Gtk.Label label8;
	private global::Gtk.Label label5;
	private global::Gtk.CheckButton australia;
	private global::Gtk.CheckButton macedonia;
	private global::Gtk.CheckButton reino;
	private global::Gtk.CheckButton chile;
	private global::Gtk.CheckButton portugal;
	private global::Gtk.Label label4;
	private global::Gtk.RadioButton monterrey;
	private global::Gtk.RadioButton guadalajara;
	private global::Gtk.RadioButton df;
	private global::Gtk.Label label3;
	private global::Gtk.Label label6;
	private global::Gtk.Label label9;
	private global::Gtk.Calendar calFecha;
	private global::Gtk.Button terminar;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Examen Final muahahaha :)");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Código");
		this.fixed1.Add (this.label1);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label1]));
		w1.X = 22;
		w1.Y = 18;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Nombre");
		this.fixed1.Add (this.label2);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label2]));
		w2.X = 246;
		w2.Y = 21;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtcodigo = new global::Gtk.Entry ();
		this.txtcodigo.CanFocus = true;
		this.txtcodigo.Name = "txtcodigo";
		this.txtcodigo.IsEditable = true;
		this.txtcodigo.InvisibleChar = '•';
		this.fixed1.Add (this.txtcodigo);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.txtcodigo]));
		w3.X = 72;
		w3.Y = 14;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtnombre = new global::Gtk.Entry ();
		this.txtnombre.CanFocus = true;
		this.txtnombre.Name = "txtnombre";
		this.txtnombre.IsEditable = true;
		this.txtnombre.InvisibleChar = '•';
		this.fixed1.Add (this.txtnombre);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.txtnombre]));
		w4.X = 309;
		w4.Y = 19;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spinEstados = new global::Gtk.SpinButton (0, 100, 1);
		this.spinEstados.CanFocus = true;
		this.spinEstados.Name = "spinEstados";
		this.spinEstados.Adjustment.PageIncrement = 10;
		this.spinEstados.ClimbRate = 1;
		this.spinEstados.Numeric = true;
		this.fixed1.Add (this.spinEstados);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.spinEstados]));
		w5.X = 38;
		w5.Y = 409;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label8 = new global::Gtk.Label ();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("que se compone México");
		this.fixed1.Add (this.label8);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label8]));
		w6.X = 38;
		w6.Y = 376;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("3.- Cantidad de estados de los ");
		this.fixed1.Add (this.label5);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label5]));
		w7.X = 18;
		w7.Y = 355;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.australia = new global::Gtk.CheckButton ();
		this.australia.CanFocus = true;
		this.australia.Name = "australia";
		this.australia.Label = global::Mono.Unix.Catalog.GetString ("Australia");
		this.australia.DrawIndicator = true;
		this.australia.UseUnderline = true;
		this.fixed1.Add (this.australia);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.australia]));
		w8.X = 40;
		w8.Y = 323;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.macedonia = new global::Gtk.CheckButton ();
		this.macedonia.CanFocus = true;
		this.macedonia.Name = "macedonia";
		this.macedonia.Label = global::Mono.Unix.Catalog.GetString ("Macedonia");
		this.macedonia.DrawIndicator = true;
		this.macedonia.UseUnderline = true;
		this.fixed1.Add (this.macedonia);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.macedonia]));
		w9.X = 41;
		w9.Y = 296;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.reino = new global::Gtk.CheckButton ();
		this.reino.CanFocus = true;
		this.reino.Name = "reino";
		this.reino.Label = global::Mono.Unix.Catalog.GetString ("Reino Unido");
		this.reino.DrawIndicator = true;
		this.reino.UseUnderline = true;
		this.fixed1.Add (this.reino);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.reino]));
		w10.X = 42;
		w10.Y = 269;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.chile = new global::Gtk.CheckButton ();
		this.chile.CanFocus = true;
		this.chile.Name = "chile";
		this.chile.Label = global::Mono.Unix.Catalog.GetString ("Chile");
		this.chile.DrawIndicator = true;
		this.chile.UseUnderline = true;
		this.fixed1.Add (this.chile);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.chile]));
		w11.X = 43;
		w11.Y = 245;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.portugal = new global::Gtk.CheckButton ();
		this.portugal.CanFocus = true;
		this.portugal.Name = "portugal";
		this.portugal.Label = global::Mono.Unix.Catalog.GetString ("Portugal");
		this.portugal.DrawIndicator = true;
		this.portugal.UseUnderline = true;
		this.fixed1.Add (this.portugal);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.portugal]));
		w12.X = 43;
		w12.Y = 220;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("2.- Paises de Europa");
		this.fixed1.Add (this.label4);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label4]));
		w13.X = 15;
		w13.Y = 190;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.monterrey = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Monterrey"));
		this.monterrey.CanFocus = true;
		this.monterrey.Name = "monterrey";
		this.monterrey.DrawIndicator = true;
		this.monterrey.UseUnderline = true;
		this.monterrey.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.fixed1.Add (this.monterrey);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.monterrey]));
		w14.X = 28;
		w14.Y = 157;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.guadalajara = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Guadalajara"));
		this.guadalajara.CanFocus = true;
		this.guadalajara.Name = "guadalajara";
		this.guadalajara.DrawIndicator = true;
		this.guadalajara.UseUnderline = true;
		this.guadalajara.Group = this.monterrey.Group;
		this.fixed1.Add (this.guadalajara);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.guadalajara]));
		w15.X = 29;
		w15.Y = 130;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.df = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("DF"));
		this.df.CanFocus = true;
		this.df.Name = "df";
		this.df.DrawIndicator = true;
		this.df.UseUnderline = true;
		this.df.Group = this.monterrey.Group;
		this.fixed1.Add (this.df);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.df]));
		w16.X = 31;
		w16.Y = 102;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("1.- Capital de México");
		this.fixed1.Add (this.label3);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label3]));
		w17.X = 15;
		w17.Y = 78;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("4.- Día que termino la segunda ");
		this.fixed1.Add (this.label6);
		global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label6]));
		w18.X = 256;
		w18.Y = 79;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label9 = new global::Gtk.Label ();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("guerra mundial");
		this.fixed1.Add (this.label9);
		global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label9]));
		w19.X = 273;
		w19.Y = 100;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.calFecha = new global::Gtk.Calendar ();
		this.calFecha.CanFocus = true;
		this.calFecha.Name = "calFecha";
		this.calFecha.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
		this.fixed1.Add (this.calFecha);
		global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.calFecha]));
		w20.X = 238;
		w20.Y = 135;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.terminar = new global::Gtk.Button ();
		this.terminar.CanFocus = true;
		this.terminar.Name = "terminar";
		this.terminar.UseUnderline = true;
		this.terminar.Label = global::Mono.Unix.Catalog.GetString ("Terminar");
		this.fixed1.Add (this.terminar);
		global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.terminar]));
		w21.X = 450;
		w21.Y = 407;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 549;
		this.DefaultHeight = 485;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.terminar.Clicked += new global::System.EventHandler (this.OnTerminarClicked);
	}
}
